### ISSUE TITLE
I tried to fix some errors that Markbot pointed out but I havent found out any solution

### ISSUE THREAD

**Issue by hoanganhduong** [hoanganhduong/accessibility-fixer-upper#1]
1. I tried nav a:focus but Markbot still required :focus state for the navigation links.
2. Apparently the skip links don't really work when I hit tab.

@muxlowc

**Comment by muxlowc** [comment]
@hoanganhduong 

1) you will have to add a class="nav" to your nav, and then in your css add:

.nav a:hover,
.nav a:focus {
  background-color: #fff;
  color: #113c00;
}

2) Hm yah, so it seems like Markbot only wants two skip links:
```
  <ul class="skip-links">
    <li><a href="#nav">Skip to navigation</a></li>
    <li><a href="#main">Skip to the main content</a></li>
  </ul>
```

**Comment by hoanganhduong** [comment]
Perfect. This helps a lot
